N1 = (input('please enter a noun: '))
print("")
print("Noun: {NA}" .format(NA=N1))
print("")
V1 = (input('please enter a verb: '))
print("")
print("Verb: {VA}" .format(VA=V1))
print("")
A1 = (input('please enter a adjective: '))
print("")
print("Adjective: {AA}" .format(AA=A1))
print("")
P1 = (input('please enter a place: '))
print("")
print("place: {PA}" .format(PA=P1))
print("")
print("")
print("")
print("")
print("")
print("steal that"),print(A1),print(N1),print("and"),print(V1),print("it in the"),print(P1)

